[build]
  publish = "dist"
  command = "npm run build"

[[edge_functions]]
  function = "og-blog"
  path = "/blog"

[[edge_functions]]
  function = "og-blog"
  path = "/blog/*"

[[headers]]
  for = "/blog/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
