import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'preheader.trial': '✨ Menus personnalisés — Satisfait ou remboursé 30 jours',
    'signup.title': 'Commencer avec NutriZen',
    'signup.subtitle': 'Crée ton compte et choisis ta formule',
    'signup.info': 'Formules Starter et Premium. Sans engagement.',
    'signup.benefit': '🔒 Paiement sécurisé Stripe',
    'signup.viewPlans': 'Voir les formules',
    'signup.hasAccount': 'Déjà un compte ?',
    'signup.login': 'Se connecter',
    'signup.backHome': "← Retour à l'accueil",
    'header.advantages': 'Avantages',
    'header.howItWorks': 'Fonctionnement',
    'header.examples': 'Exemples',
    'header.pricing': 'Tarifs',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Se connecter',
    'header.cta': 'Choisir ma formule',
    'hero.badge': '🔥 +1 000 utilisateurs',
    'hero.badgeSuffix': '· Sans engagement',
    'hero.title': 'Menus adaptés à tes objectifs en 30 secondes',
    'hero.subtitle': 'Sans passer des heures à réfléchir, planifier et calculer.',
    'hero.benefit1': 'Gagne 5h par semaine',
    'hero.benefit1Desc': 'sur ta planification repas',
    'hero.benefit2': 'Ton plan adapté',
    'hero.benefit2Desc': 'à tes objectifs (perte, maintien, prise)',
    'hero.benefit3': 'Plus de prise de tête',
    'hero.benefit3Desc': ': tout est calculé pour toi',
    'hero.cta': 'Choisir ma formule',
    'hero.trial': 'Sans engagement',
    'hero.trialDetails': '· Satisfait ou remboursé 30 jours',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2 400 avis',
    'hero.cancelAnytime': 'Annulable en 3 clics',
    'hero.guarantee': 'Garantie temps-gagné 30j',
    'hero.validated': 'Validé par diététicien(ne)',
    'hero.menuGenerated': 'Menu généré',
    'hero.autoShoppingList': 'Courses auto',
    'benefits.title': 'Pourquoi choisir myNutriZen ?',
    'benefits.1.title': 'Gagne 5h par semaine',
    'benefits.1.result': 'Plus de temps pour toi',
    'benefits.1.description':
      'Fini les 30 min quotidiennes à te demander "qu\'est-ce qu\'on mange ?". Tout est planifié automatiquement.',
    'benefits.2.title': "Économise jusqu'à 30%",
    'benefits.2.result': 'Liste de courses optimisée',
    'benefits.2.description':
      'Ton plan génère une liste précise par rayon. Exit les achats impulsifs et le gaspillage.',
    'benefits.3.title': 'Zéro charge mentale',
    'benefits.3.result': 'Menus équilibrés automatiques',
    'benefits.3.description':
      'Ton plan adapté à tes objectifs (perte, maintien, prise). Tout est calculé et prêt en 1 clic.',
    'howItWorks.title': 'Comment ça marche ?',
    'howItWorks.subtitle': '3 étapes simples pour simplifier tes repas',
    'howItWorks.step1.title': 'Réponds à 3 questions en 60 s',
    'howItWorks.step1.description': 'Profils, goûts, objectifs — on crée ton plan.',
    'howItWorks.step2.title': 'Reçois ton plan repas généré automatiquement',
    'howItWorks.step2.description': 'Chaque jour un menu complet adapté à ton rythme.',
    'howItWorks.step3.title': 'Swap libre & profite',
    'howItWorks.step3.description':
      'Un plat ne te plaît pas ? Change-le en un clic. Gain de temps. Zéro stress.',
    'personas.title': 'Est-ce pour moi ?',
    'personas.subtitle': "Choisis ton profil pour voir comment NutriZen s'adapte à tes objectifs",
    'personas.muscu.title': 'Muscu / Prise de masse',
    'personas.muscu.description':
      'Tu veux prendre du muscle sans te prendre la tête avec les macros.',
    'personas.muscu.cta': "C'est moi",
    'personas.crossfit.title': 'CrossFit / WOD',
    'personas.crossfit.description':
      'Tu veux performer sans passer 3h à préparer tes repas le dimanche.',
    'personas.crossfit.cta': "C'est moi",
    'personas.running.title': 'Running / Endurance',
    'personas.running.description': 'Tu veux éviter le mur au km 30 avec une nutrition claire.',
    'personas.running.cta': "C'est moi",
    'pas.tag': 'Tu te reconnais ?',
    'pas.title': 'Arrête de perdre du temps',
    'pas.resultNote': "Résultat : tu perds du temps, de l'argent, et tes objectifs stagnent.",
    'pas.solutionTag': 'La solution',
    'pas.solutionTitle': "NutriZen s'occupe de tout",
    'pas.solution1': 'Menus orientés objectifs en 30 secondes',
    'pas.solution2': 'Liste de courses automatique',
    'pas.solution3': 'Swaps intelligents en 1 clic',
    'pas.solution4': 'Astuce quotidienne personnalisée',
    'pas.benefitsTitle': 'Les bénéfices :',
    'exampleWeek.title': 'À quoi ressemble une semaine ?',
    'exampleWeek.subtitle': 'Voici un exemple de plan hebdomadaire généré en 30 secondes',
    'exampleWeek.breakfast': 'Petit-déjeuner',
    'exampleWeek.lunch': 'Déjeuner',
    'exampleWeek.dinner': 'Dîner',
    'exampleWeek.kcal': 'kcal',
    'exampleWeek.protein': 'Protéines',
    'exampleWeek.carbs': 'Glucides',
    'exampleWeek.fat': 'Lipides',
    'exampleWeek.shoppingList': 'Voir la liste de courses',
    'exampleWeek.shoppingListTitle': 'Liste de courses de la semaine',
    'exampleWeek.note': '💡 Macros indicatives — adaptées selon tes objectifs et ton profil',
    'recipes.title': 'Des recettes équilibrées, gourmandes et faciles',
    'recipes.subtitle':
      'Créées par notre équipe de nutritionnistes pour tous les goûts et budgets.',
    'economic.title': 'Tes économies avec NutriZen',
    'economic.subtitle': 'Des chiffres réels de nos utilisateurs',
    'economic.intro': 'En moyenne, nos utilisateurs :',
    'economic.time': 'gagnées par semaine',
    'economic.timeNote': 'Plus besoin de passer du temps à chercher des recettes et planifier',
    'economic.savings': 'économisés par mois',
    'economic.savingsNote': 'En réduisant le gaspillage alimentaire et les achats impulsifs',
    'economic.yearTotal': "Soit 2 400€ d'économies par an",
    'economic.timeTotal': 'Et 156 heures de temps libre récupéré',
    'value.title': 'Ce que tu obtiens',
    'value.subtitle': 'La valeur réelle de ton abonnement',
    'value.advantage': 'Avantage',
    'value.value': 'Valeur',
    'value.menus': 'Menus personnalisés chaque semaine',
    'value.recipes': 'Recettes équilibrées et rapides',
    'value.shopping': 'Liste de courses intelligente',
    'value.advice': 'Conseils nutritionnels',
    'value.tracking': 'Suivi de tes progrès',
    'value.scanRepas': 'ScanRepas - Analyse photos de repas',
    'value.total': 'Total valeur',
    'value.yourPrice': 'Ton prix NutriZen',
    'value.saving': 'Options premium via Crédits Zen',
    'value.trial': '(Sans engagement)',
    'pricing.title': 'Commence gratuitement, active les options quand tu veux',
    'pricing.subtitle': 'Compte gratuit complet. Crédits Zen optionnels.',
    'pricing.monthly': 'Mensuel',
    'pricing.annual': 'Annuel',
    'pricing.discount': '-2 mois',
    'pricing.valueAnchor': 'Valeur réelle estimée :',
    'pricing.yourPrice': "Ton tarif aujourd'hui :",
    'pricing.feature1': '50+ recettes exclusives',
    'pricing.feature2': 'Support prioritaire',
    'pricing.feature3': 'Crédits non expirants',
    'pricing.trial': '🔒 Satisfait ou remboursé 30 jours',
    'pricing.note': '✅ Sans engagement — Annulable à tout moment',
    'testimonials.title': "Rejoignez une communauté de milliers d'utilisateurs comblés",
    'testimonials.rating': 'avis',
    'guarantee.title': 'Garantie Satisfait ou remboursé',
    'guarantee.description':
      "Si après 30 jours d'utilisation, tu constates que tu n'as pas gagné de temps avec NutriZen, contacte-nous. Nous te remboursons intégralement, sans questions compliquées.",
    'urgency.title': 'Offre limitée',
    'urgency.description1':
      'Rejoins les milliers de familles qui simplifient leurs repas avec NutriZen.',
    'urgency.description2': 'Choisis ta formule dès maintenant.',
    'urgency.cta': 'Choisir ma formule',
    'faq.title': 'Questions fréquentes',
    'faq.subtitle': 'Tout ce que tu dois savoir sur NutriZen',
    'finalCta.title': 'Prêt à simplifier tes repas ?',
    'finalCta.cta': 'Choisir ma formule',
    'footer.resources': 'Ressources',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.legal': 'Légal',
    'footer.cgv': 'CGV',
    'footer.privacy': 'Confidentialité',
    'footer.mentions': 'Mentions légales',
    'footer.company': 'Entreprise',
    'footer.about': 'À propos',
    'footer.offers': 'Nos offres',
    'footer.fit': 'NutriZen Fit',
    'footer.mum': 'NutriZen Mum',
    'footer.pro': 'NutriZen Pro',
    'footer.tagline':
      'Menus adaptés à tes objectifs en 30 secondes.\nSans passer des heures à réfléchir, planifier et calculer.',
    'footer.copyright': '© 2026 NutriZen. Tous droits réservés.',
    'footer.disclaimer':
      "NutriZen est un assistant d'organisation de repas, pas un professionnel de santé. Les informations fournies ne constituent pas un avis médical. Consulte un médecin ou diététicien(ne) pour des conseils personnalisés.",
  },
  en: {
    'preheader.trial': '✨ Personalized menus — 30-day money-back guarantee',
    'signup.title': 'Get Started with NutriZen',
    'signup.subtitle': 'Create your account and pick a plan',
    'signup.info': 'Starter and Premium plans. Cancel anytime.',
    'signup.benefit': '🔒 Secure Stripe payment',
    'signup.viewPlans': 'View Plans',
    'signup.hasAccount': 'Already have an account?',
    'signup.login': 'Sign in',
    'signup.backHome': '← Back to home',
    'header.advantages': 'Benefits',
    'header.howItWorks': 'How It Works',
    'header.examples': 'Examples',
    'header.pricing': 'Pricing',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Sign in',
    'header.cta': 'Choose my plan',
    'hero.badge': '🔥 +1,000 users',
    'hero.badgeSuffix': '· Free forever',
    'hero.title': 'Menus tailored to your goals in 30 seconds',
    'hero.subtitle': 'Without spending hours thinking, planning, and calculating.',
    'hero.benefit1': 'Save 5h per week',
    'hero.benefit1Desc': 'on your meal planning',
    'hero.benefit2': 'Your personalized plan',
    'hero.benefit2Desc': 'for your goals (loss, maintenance, gain)',
    'hero.benefit3': 'No more hassle',
    'hero.benefit3Desc': ': everything calculated for you',
    'hero.cta': 'Choose my plan',
    'hero.trial': 'No commitment',
    'hero.trialDetails': '· 30-day money-back guarantee',
    'hero.rating': '4.8/5',
    'hero.reviews': '+2,400 reviews',
    'hero.cancelAnytime': 'Cancel anytime in 3 clicks',
    'hero.guarantee': '30-day time-saved guarantee',
    'hero.validated': 'Dietitian validated',
    'hero.menuGenerated': 'Menu generated',
    'hero.autoShoppingList': 'Auto shopping list',
    'benefits.title': 'Why choose myNutriZen?',
    'benefits.1.title': 'Save 5h per week',
    'benefits.1.result': 'More time for you',
    'benefits.1.description':
      'No more 30 daily minutes wondering "what to eat?". Everything is planned automatically.',
    'benefits.2.title': 'Save up to 30%',
    'benefits.2.result': 'Optimized shopping list',
    'benefits.2.description':
      'Your plan generates a precise list by aisle. No more impulse purchases and waste.',
    'benefits.3.title': 'Zero mental load',
    'benefits.3.result': 'Automatic balanced menus',
    'benefits.3.description':
      'Your plan adapted to your goals (loss, maintenance, gain). Everything calculated and ready in 1 click.',
    'howItWorks.title': 'How does it work?',
    'howItWorks.subtitle': '3 simple steps to simplify your meals',
    'howItWorks.step1.title': 'Answer 3 questions in 60s',
    'howItWorks.step1.description': 'Profiles, tastes, goals — we create your plan.',
    'howItWorks.step2.title': 'Receive your automatically generated meal plan',
    'howItWorks.step2.description': 'Every day a complete menu adapted to your rhythm.',
    'howItWorks.step3.title': 'Free swap & enjoy',
    'howItWorks.step3.description':
      "Don't like a dish? Change it in one click. Time saved. Zero stress.",
    'personas.title': 'Is it for me?',
    'personas.subtitle': 'Choose your profile to see how NutriZen adapts to your goals',
    'personas.muscu.title': 'Muscle Building / Mass Gain',
    'personas.muscu.description': 'You want to build muscle without stressing about macros.',
    'personas.muscu.cta': "That's me",
    'personas.crossfit.title': 'CrossFit / WOD',
    'personas.crossfit.description':
      'You want to perform without spending 3h preparing meals on Sunday.',
    'personas.crossfit.cta': "That's me",
    'personas.running.title': 'Running / Endurance',
    'personas.running.description':
      'You want to avoid hitting the wall at km 30 with clear nutrition.',
    'personas.running.cta': "That's me",
    'pas.tag': 'Do you recognize yourself?',
    'pas.title': 'Stop wasting time',
    'pas.resultNote': 'Result: you lose time, money, and your goals stagnate.',
    'pas.solutionTag': 'The solution',
    'pas.solutionTitle': 'NutriZen takes care of everything',
    'pas.solution1': 'Goal-oriented menus in 30 seconds',
    'pas.solution2': 'Automatic shopping list',
    'pas.solution3': 'Smart swaps in 1 click',
    'pas.solution4': 'Personalized daily tip',
    'pas.benefitsTitle': 'The benefits:',
    'exampleWeek.title': 'What does a week look like?',
    'exampleWeek.subtitle': "Here's an example of a weekly plan generated in 30 seconds",
    'exampleWeek.breakfast': 'Breakfast',
    'exampleWeek.lunch': 'Lunch',
    'exampleWeek.dinner': 'Dinner',
    'exampleWeek.kcal': 'kcal',
    'exampleWeek.protein': 'Protein',
    'exampleWeek.carbs': 'Carbs',
    'exampleWeek.fat': 'Fat',
    'exampleWeek.shoppingList': 'View shopping list',
    'exampleWeek.shoppingListTitle': 'Weekly shopping list',
    'exampleWeek.note': '💡 Indicative macros — adapted to your goals and profile',
    'recipes.title': 'Balanced, delicious, and easy recipes',
    'recipes.subtitle': 'Created by our team of nutritionists for all tastes and budgets.',
    'economic.title': 'Your savings with NutriZen',
    'economic.subtitle': 'Real figures from our users',
    'economic.intro': 'On average, our users:',
    'economic.time': 'saved per week',
    'economic.timeNote': 'No more time spent searching for recipes and planning',
    'economic.savings': 'saved per month',
    'economic.savingsNote': 'By reducing food waste and impulse purchases',
    'economic.yearTotal': "That's €2,400 in savings per year",
    'economic.timeTotal': 'And 156 hours of free time recovered',
    'value.title': 'What you get',
    'value.subtitle': 'The real value of your subscription',
    'value.advantage': 'Benefit',
    'value.value': 'Value',
    'value.menus': 'Personalized weekly menus',
    'value.recipes': 'Balanced and quick recipes',
    'value.shopping': 'Smart shopping list',
    'value.advice': 'Nutritional advice',
    'value.tracking': 'Progress tracking',
    'value.scanRepas': 'ScanRepas - Meal photo analysis',
    'value.total': 'Total value',
    'value.yourPrice': 'Your NutriZen price',
    'value.saving': 'Premium options via Zen Credits',
    'value.trial': '(No commitment)',
    'pricing.title': 'Start free, unlock options when you need them',
    'pricing.subtitle': 'Full free account. Optional Zen Credits.',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.discount': '-2 months',
    'pricing.valueAnchor': 'Estimated real value:',
    'pricing.yourPrice': 'Your price today:',
    'pricing.feature1': '50+ exclusive recipes',
    'pricing.feature2': 'Priority support',
    'pricing.feature3': 'Non-expiring credits',
    'pricing.trial': '🔒 30-day money-back guarantee',
    'pricing.note': '✅ No commitment — Cancel anytime',
    'testimonials.title': 'Join a community of thousands of satisfied users',
    'testimonials.rating': 'reviews',
    'guarantee.title': 'Secure Payment',
    'guarantee.description':
      'Zen Credits are purchased once and never expire. You can use them whenever you want, no pressure.',
    'urgency.title': 'Get Started',
    'urgency.description1':
      'Join thousands of families who have simplified their meals with NutriZen.',
    'urgency.description2': 'Pick your plan now.',
    'urgency.cta': 'Get Started Free',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about NutriZen',
    'finalCta.title': 'Ready to simplify your meals?',
    'finalCta.cta': 'Get Started Free',
    'finalCta.note': 'No credit card required',
    'footer.resources': 'Resources',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.cgv': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.mentions': 'Legal Notice',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.offers': 'Our Offers',
    'footer.fit': 'NutriZen Fit',
    'footer.mum': 'NutriZen Mum',
    'footer.pro': 'NutriZen Pro',
    'footer.tagline':
      'Menus tailored to your goals in 30 seconds.\nWithout spending hours thinking, planning, and calculating.',
    'footer.copyright': '© 2025 NutriZen. All rights reserved.',
    'footer.disclaimer':
      'NutriZen is a meal organization assistant, not a healthcare professional. The information provided does not constitute medical advice. Consult a doctor or dietitian for personalized advice.',
  },
  es: {
    'preheader.trial':
      '🎉 Prueba gratuita de 7 días — Sin tarjeta de crédito — Garantía de tiempo ahorrado de 30 días',
    'signup.title': 'Comienza con NutriZen',
    'signup.subtitle': 'Elige tu plan para crear tu cuenta',
    'signup.info':
      'Para garantizar la calidad de nuestro servicio, la creación de cuentas se realiza exclusivamente a través de Stripe.',
    'signup.benefit': '🎁 Prueba gratuita de 7 días · Sin tarjeta de crédito requerida',
    'signup.viewPlans': 'Ver Planes',
    'signup.hasAccount': '¿Ya tienes una cuenta?',
    'signup.login': 'Iniciar sesión',
    'signup.backHome': '← Volver al inicio',
    'header.advantages': 'Ventajas',
    'header.howItWorks': 'Cómo Funciona',
    'header.examples': 'Ejemplos',
    'header.pricing': 'Precios',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Iniciar sesión',
    'header.cta': 'Comenzar Gratis',
    'hero.badge': '🔥 +1.000 usuarios',
    'hero.badgeSuffix': '· 92% continúan después de la prueba',
    'hero.title': 'Menús adaptados a tus objetivos en 30 segundos',
    'hero.subtitle': 'Sin pasar horas pensando, planificando y calculando.',
    'hero.benefit1': 'Ahorra 5h por semana',
    'hero.benefit1Desc': 'en tu planificación de comidas',
    'hero.benefit2': 'Tu plan personalizado',
    'hero.benefit2Desc': 'para tus objetivos (pérdida, mantenimiento, ganancia)',
    'hero.benefit3': 'Sin complicaciones',
    'hero.benefit3Desc': ': todo calculado para ti',
    'hero.cta': 'Comenzar mi prueba gratuita de 7 días',
    'hero.trial': 'Prueba gratuita de 7 días',
    'hero.trialDetails': '· Sin compromiso · Sin tarjeta de crédito requerida',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2.400 reseñas',
    'hero.cancelAnytime': 'Cancela en cualquier momento en 3 clics',
    'hero.guarantee': 'Garantía de tiempo ahorrado de 30 días',
    'hero.validated': 'Validado por nutricionista',
    'hero.menuGenerated': 'Menú generado',
    'hero.autoShoppingList': 'Lista de compras automática',
    'benefits.title': '¿Por qué elegir myNutriZen?',
    'benefits.1.title': 'Ahorra 5h por semana',
    'benefits.1.result': 'Más tiempo para ti',
    'benefits.1.description':
      'Se acabaron los 30 minutos diarios preguntándote "¿qué comemos?". Todo está planificado automáticamente.',
    'benefits.2.title': 'Ahorra hasta un 30%',
    'benefits.2.result': 'Lista de compras optimizada',
    'benefits.2.description':
      'Tu plan genera una lista precisa por pasillo. Adiós a las compras impulsivas y el desperdicio.',
    'benefits.3.title': 'Cero carga mental',
    'benefits.3.result': 'Menús equilibrados automáticos',
    'benefits.3.description':
      'Tu plan adaptado a tus objetivos (pérdida, mantenimiento, ganancia). Todo calculado y listo en 1 clic.',
    'howItWorks.title': '¿Cómo funciona?',
    'howItWorks.subtitle': '3 pasos simples para simplificar tus comidas',
    'howItWorks.step1.title': 'Responde 3 preguntas en 60s',
    'howItWorks.step1.description': 'Perfiles, gustos, objetivos: creamos tu plan.',
    'howItWorks.step2.title': 'Recibe tu plan de comidas generado automáticamente',
    'howItWorks.step2.description': 'Cada día un menú completo adaptado a tu ritmo.',
    'howItWorks.step3.title': 'Intercambio libre y disfruta',
    'howItWorks.step3.description':
      '¿No te gusta un plato? Cámbialo en un clic. Ahorro de tiempo. Cero estrés.',
    'personas.title': '¿Es para mí?',
    'personas.subtitle': 'Elige tu perfil para ver cómo NutriZen se adapta a tus objetivos',
    'personas.muscu.title': 'Musculación / Aumento de masa',
    'personas.muscu.description': 'Quieres ganar músculo sin complicarte con las macros.',
    'personas.muscu.cta': 'Soy yo',
    'personas.crossfit.title': 'CrossFit / WOD',
    'personas.crossfit.description': 'Quieres rendir sin pasar 3h preparando comidas el domingo.',
    'personas.crossfit.cta': 'Soy yo',
    'personas.running.title': 'Running / Resistencia',
    'personas.running.description': 'Quieres evitar el muro en el km 30 con una nutrición clara.',
    'personas.running.cta': 'Soy yo',
    'pas.tag': '¿Te reconoces?',
    'pas.title': 'Deja de perder tiempo',
    'pas.resultNote': 'Resultado: pierdes tiempo, dinero y tus objetivos se estancan.',
    'pas.solutionTag': 'La solución',
    'pas.solutionTitle': 'NutriZen se encarga de todo',
    'pas.solution1': 'Menús orientados a objetivos en 30 segundos',
    'pas.solution2': 'Lista de compras automática',
    'pas.solution3': 'Intercambios inteligentes en 1 clic',
    'pas.solution4': 'Consejo diario personalizado',
    'pas.benefitsTitle': 'Los beneficios:',
    'exampleWeek.title': '¿Cómo es una semana?',
    'exampleWeek.subtitle': 'Aquí tienes un ejemplo de plan semanal generado en 30 segundos',
    'exampleWeek.breakfast': 'Desayuno',
    'exampleWeek.lunch': 'Almuerzo',
    'exampleWeek.dinner': 'Cena',
    'exampleWeek.kcal': 'kcal',
    'exampleWeek.protein': 'Proteínas',
    'exampleWeek.carbs': 'Carbohidratos',
    'exampleWeek.fat': 'Grasas',
    'exampleWeek.shoppingList': 'Ver lista de compras',
    'exampleWeek.shoppingListTitle': 'Lista de compras semanal',
    'exampleWeek.note': '💡 Macros indicativas — adaptadas a tus objetivos y perfil',
    'recipes.title': 'Recetas equilibradas, deliciosas y fáciles',
    'recipes.subtitle':
      'Creadas por nuestro equipo de nutricionistas para todos los gustos y presupuestos.',
    'economic.title': 'Tus ahorros con NutriZen',
    'economic.subtitle': 'Cifras reales de nuestros usuarios',
    'economic.intro': 'En promedio, nuestros usuarios:',
    'economic.time': 'ahorradas por semana',
    'economic.timeNote': 'No más tiempo buscando recetas y planificando',
    'economic.savings': 'ahorrados por mes',
    'economic.savingsNote': 'Reduciendo el desperdicio de alimentos y las compras impulsivas',
    'economic.yearTotal': 'Eso es 2.400€ de ahorro al año',
    'economic.timeTotal': 'Y 156 horas de tiempo libre recuperado',
    'value.title': 'Lo que obtienes',
    'value.subtitle': 'El valor real de tu suscripción',
    'value.advantage': 'Ventaja',
    'value.value': 'Valor',
    'value.menus': 'Menús personalizados semanales',
    'value.recipes': 'Recetas equilibradas y rápidas',
    'value.shopping': 'Lista de compras inteligente',
    'value.advice': 'Consejos nutricionales',
    'value.tracking': 'Seguimiento de progresos',
    'value.scanRepas': 'ScanRepas - Análisis de fotos de comidas',
    'value.total': 'Valor total',
    'value.yourPrice': 'Tu precio NutriZen',
    'value.saving': 'Ahorras 185 €/mes',
    'value.trial': '(Prueba gratuita de 7 días)',
    'pricing.title': 'Elige tu plan y comienza hoy',
    'pricing.subtitle': 'Precios simples y transparentes. Siempre cancelable en 3 clics.',
    'pricing.monthly': 'Mensual',
    'pricing.annual': 'Anual',
    'pricing.discount': '-2 meses',
    'pricing.valueAnchor': 'Valor real estimado:',
    'pricing.yourPrice': 'Tu precio hoy:',
    'pricing.feature1': '50+ recetas exclusivas',
    'pricing.feature2': 'Soporte prioritario',
    'pricing.feature3': 'Garantía 30 días',
    'pricing.trial': '🔥 Prueba gratuita de 7 días — sin tarjeta de crédito',
    'pricing.note':
      '✅ Satisfecho o reembolsado — Garantía de 30 días de tiempo ahorrado • Cancelable en 3 clics',
    'testimonials.title': 'Únete a una comunidad de miles de usuarios satisfechos',
    'testimonials.rating': 'reseñas',
    'guarantee.title': 'Garantía de satisfacción o reembolso',
    'guarantee.description':
      'Si después de 30 días de uso, encuentras que no has ahorrado tiempo con NutriZen, contáctanos. Te reembolsaremos completamente, sin preguntas complicadas.',
    'urgency.title': 'Oferta limitada',
    'urgency.description1':
      'Solo los primeros 100 inscritos se benefician del valor completo de 200 € al precio de 19,99 €/mes. La oferta puede cambiar después de este límite.',
    'urgency.description2': 'La oferta termina el domingo a las 23:59.',
    'urgency.cta': 'Comienzo ahora mi prueba gratuita de 7 días',
    'faq.title': 'Preguntas frecuentes',
    'faq.subtitle': 'Todo lo que necesitas saber sobre NutriZen',
    'finalCta.title': 'En 7 días, ya puedes tener una semana clara en tu plato.',
    'finalCta.cta': 'Comenzar mi semana gratuita',
    'finalCta.note': 'No se requiere tarjeta de crédito',
    'footer.resources': 'Recursos',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contacto',
    'footer.legal': 'Legal',
    'footer.cgv': 'Términos',
    'footer.privacy': 'Privacidad',
    'footer.mentions': 'Aviso Legal',
    'footer.company': 'Empresa',
    'footer.about': 'Acerca de',
    'footer.offers': 'Nuestras Ofertas',
    'footer.fit': 'NutriZen Fit',
    'footer.mum': 'NutriZen Mum',
    'footer.pro': 'NutriZen Pro',
    'footer.tagline':
      'Menús adaptados a tus objetivos en 30 segundos.\nSin pasar horas pensando, planificando y calculando.',
    'footer.copyright': '© 2025 NutriZen. Todos los derechos reservados.',
    'footer.disclaimer':
      'NutriZen es un asistente de organización de comidas, no un profesional de la salud. La información proporcionada no constituye asesoramiento médico. Consulta a un médico o nutricionista para obtener asesoramiento personalizado.',
  },
  de: {
    'preheader.trial':
      '🎉 7 Tage kostenlose Testversion — Keine Kreditkarte erforderlich — 30-Tage-Zeitersparnis-Garantie',
    'signup.title': 'Starte mit NutriZen',
    'signup.subtitle': 'Wähle deinen Plan, um dein Konto zu erstellen',
    'signup.info':
      'Um die Qualität unseres Services zu gewährleisten, erfolgt die Kontoerstellung ausschließlich über Stripe.',
    'signup.benefit': '🎁 7 Tage kostenlose Testversion · Keine Kreditkarte erforderlich',
    'signup.viewPlans': 'Pläne ansehen',
    'signup.hasAccount': 'Hast du bereits ein Konto?',
    'signup.login': 'Anmelden',
    'signup.backHome': '← Zurück zur Startseite',
    'header.advantages': 'Vorteile',
    'header.howItWorks': 'Wie es funktioniert',
    'header.examples': 'Beispiele',
    'header.pricing': 'Preise',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Anmelden',
    'header.cta': 'Kostenlos starten',
    'hero.badge': '🔥 +1.000 Nutzer',
    'hero.badgeSuffix': '· 92% verlängern nach der Testphase',
    'hero.title': 'Menüs an deine Ziele angepasst in 30 Sekunden',
    'hero.subtitle': 'Ohne Stunden mit Nachdenken, Planen und Berechnen zu verbringen.',
    'hero.benefit1': 'Spare 5h pro Woche',
    'hero.benefit1Desc': 'bei deiner Essensplanung',
    'hero.benefit2': 'Dein personalisierter Plan',
    'hero.benefit2Desc': 'für deine Ziele (Abnehmen, Erhaltung, Zunehmen)',
    'hero.benefit3': 'Kein Stress mehr',
    'hero.benefit3Desc': ': alles für dich berechnet',
    'hero.cta': 'Meine 7-tägige kostenlose Testversion starten',
    'hero.trial': '7 Tage kostenlose Testversion',
    'hero.trialDetails': '· Keine Verpflichtung · Keine Kreditkarte erforderlich',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2.400 Bewertungen',
    'hero.cancelAnytime': 'Jederzeit in 3 Klicks kündbar',
    'hero.guarantee': '30-Tage-Zeitersparnis-Garantie',
    'hero.validated': 'Von Ernährungsberater validiert',
    'hero.menuGenerated': 'Menü generiert',
    'hero.autoShoppingList': 'Auto-Einkaufsliste',
    'benefits.title': 'Warum myNutriZen wählen?',
    'benefits.1.title': 'Spare 5h pro Woche',
    'benefits.1.result': 'Mehr Zeit für dich',
    'benefits.1.description':
      'Keine 30 Minuten täglich mehr mit der Frage "Was essen wir?". Alles ist automatisch geplant.',
    'benefits.2.title': 'Spare bis zu 30%',
    'benefits.2.result': 'Optimierte Einkaufsliste',
    'benefits.2.description':
      'Dein Plan erstellt eine präzise Liste nach Gang. Keine Impulskäufe und Verschwendung mehr.',
    'benefits.3.title': 'Null mentale Belastung',
    'benefits.3.result': 'Automatische ausgewogene Menüs',
    'benefits.3.description':
      'Dein Plan angepasst an deine Ziele (Abnehmen, Erhaltung, Zunehmen). Alles berechnet und bereit in 1 Klick.',
    'howItWorks.title': 'Wie funktioniert es?',
    'howItWorks.subtitle': '3 einfache Schritte zur Vereinfachung deiner Mahlzeiten',
    'howItWorks.step1.title': 'Beantworte 3 Fragen in 60s',
    'howItWorks.step1.description': 'Profile, Geschmäcker, Ziele — wir erstellen deinen Plan.',
    'howItWorks.step2.title': 'Erhalte deinen automatisch generierten Essensplan',
    'howItWorks.step2.description': 'Jeden Tag ein komplettes Menü an deinen Rhythmus angepasst.',
    'howItWorks.step3.title': 'Freier Tausch & genieße',
    'howItWorks.step3.description':
      'Magst du ein Gericht nicht? Ändere es mit einem Klick. Zeitersparnis. Null Stress.',
    'personas.title': 'Ist es für mich?',
    'personas.subtitle': 'Wähle dein Profil, um zu sehen, wie sich NutriZen an deine Ziele anpasst',
    'personas.muscu.title': 'Muskelaufbau / Massezunahme',
    'personas.muscu.description': 'Du willst Muskeln aufbauen, ohne dich mit Makros zu stressen.',
    'personas.muscu.cta': 'Das bin ich',
    'personas.crossfit.title': 'CrossFit / WOD',
    'personas.crossfit.description':
      'Du willst performen, ohne 3 Stunden am Sonntag mit der Essenszubereitung zu verbringen.',
    'personas.crossfit.cta': 'Das bin ich',
    'personas.running.title': 'Laufen / Ausdauer',
    'personas.running.description': 'Du willst bei km 30 nicht einbrechen mit klarer Ernährung.',
    'personas.running.cta': 'Das bin ich',
    'pas.tag': 'Erkennst du dich wieder?',
    'pas.title': 'Hör auf, Zeit zu verschwenden',
    'pas.resultNote': 'Ergebnis: Du verlierst Zeit, Geld und deine Ziele stagnieren.',
    'pas.solutionTag': 'Die Lösung',
    'pas.solutionTitle': 'NutriZen kümmert sich um alles',
    'pas.solution1': 'Zielorientierte Menüs in 30 Sekunden',
    'pas.solution2': 'Automatische Einkaufsliste',
    'pas.solution3': 'Intelligente Tausche in 1 Klick',
    'pas.solution4': 'Personalisierter täglicher Tipp',
    'pas.benefitsTitle': 'Die Vorteile:',
    'exampleWeek.title': 'Wie sieht eine Woche aus?',
    'exampleWeek.subtitle': 'Hier ist ein Beispiel eines in 30 Sekunden generierten Wochenplans',
    'exampleWeek.breakfast': 'Frühstück',
    'exampleWeek.lunch': 'Mittagessen',
    'exampleWeek.dinner': 'Abendessen',
    'exampleWeek.kcal': 'kcal',
    'exampleWeek.protein': 'Protein',
    'exampleWeek.carbs': 'Kohlenhydrate',
    'exampleWeek.fat': 'Fett',
    'exampleWeek.shoppingList': 'Einkaufsliste ansehen',
    'exampleWeek.shoppingListTitle': 'Wöchentliche Einkaufsliste',
    'exampleWeek.note': '💡 Indikative Makros — angepasst an deine Ziele und dein Profil',
    'recipes.title': 'Ausgewogene, leckere und einfache Rezepte',
    'recipes.subtitle':
      'Erstellt von unserem Team von Ernährungsberatern für alle Geschmäcker und Budgets.',
    'economic.title': 'Deine Ersparnisse mit NutriZen',
    'economic.subtitle': 'Echte Zahlen von unseren Nutzern',
    'economic.intro': 'Im Durchschnitt unsere Nutzer:',
    'economic.time': 'pro Woche gespart',
    'economic.timeNote': 'Keine Zeit mehr mit Rezeptsuche und Planung verbringen',
    'economic.savings': 'pro Monat gespart',
    'economic.savingsNote': 'Durch Reduzierung von Lebensmittelverschwendung und Impulskäufen',
    'economic.yearTotal': 'Das sind 2.400€ Ersparnis pro Jahr',
    'economic.timeTotal': 'Und 156 Stunden freie Zeit zurückgewonnen',
    'value.title': 'Was du bekommst',
    'value.subtitle': 'Der echte Wert deines Abonnements',
    'value.advantage': 'Vorteil',
    'value.value': 'Wert',
    'value.menus': 'Wöchentliche personalisierte Menüs',
    'value.recipes': 'Ausgewogene und schnelle Rezepte',
    'value.shopping': 'Intelligente Einkaufsliste',
    'value.advice': 'Ernährungsberatung',
    'value.tracking': 'Fortschrittsverfolgung',
    'value.scanRepas': 'ScanRepas - Mahlzeitfotoanalyse',
    'value.total': 'Gesamtwert',
    'value.yourPrice': 'Dein NutriZen-Preis',
    'value.saving': 'Du sparst 185 €/Monat',
    'value.trial': '(7 Tage kostenlose Testversion)',
    'pricing.title': 'Wähle deinen Plan und starte heute',
    'pricing.subtitle': 'Einfache und transparente Preise. Immer in 3 Klicks kündbar.',
    'pricing.monthly': 'Monatlich',
    'pricing.annual': 'Jährlich',
    'pricing.discount': '-2 Monate',
    'pricing.valueAnchor': 'Geschätzter echter Wert:',
    'pricing.yourPrice': 'Dein Preis heute:',
    'pricing.feature1': '50+ exklusive Rezepte',
    'pricing.feature2': 'Prioritätssupport',
    'pricing.feature3': '30-Tage-Garantie',
    'pricing.trial': '🔥 7 Tage kostenlose Testversion — keine Kreditkarte',
    'pricing.note':
      '✅ Zufrieden oder Geld zurück — 30-Tage-Zeitersparnis-Garantie • In 3 Klicks kündbar',
    'testimonials.title': 'Tritt einer Gemeinschaft von Tausenden zufriedenen Nutzern bei',
    'testimonials.rating': 'Bewertungen',
    'guarantee.title': 'Zufriedenheitsgarantie oder Geld zurück',
    'guarantee.description':
      'Wenn du nach 30 Tagen Nutzung feststellst, dass du mit NutriZen keine Zeit gespart hast, kontaktiere uns. Wir erstatten dir den vollen Betrag, ohne komplizierte Fragen.',
    'urgency.title': 'Begrenztes Angebot',
    'urgency.description1':
      'Nur die ersten 100 Abonnenten profitieren vom vollen Wert von 200 € zum Preis von 19,99 €/Monat. Das Angebot kann sich nach dieser Grenze ändern.',
    'urgency.description2': 'Das Angebot endet Sonntag um 23:59 Uhr.',
    'urgency.cta': 'Ich starte jetzt meine 7-tägige kostenlose Testversion',
    'faq.title': 'Häufig gestellte Fragen',
    'faq.subtitle': 'Alles, was du über NutriZen wissen musst',
    'finalCta.title': 'In 7 Tagen kannst du bereits eine klare Woche auf deinem Teller haben.',
    'finalCta.cta': 'Meine kostenlose Woche starten',
    'finalCta.note': 'Keine Kreditkarte erforderlich',
    'footer.resources': 'Ressourcen',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Rechtliches',
    'footer.cgv': 'AGB',
    'footer.privacy': 'Datenschutz',
    'footer.mentions': 'Impressum',
    'footer.company': 'Unternehmen',
    'footer.about': 'Über uns',
    'footer.offers': 'Unsere Angebote',
    'footer.fit': 'NutriZen Fit',
    'footer.mum': 'NutriZen Mum',
    'footer.pro': 'NutriZen Pro',
    'footer.tagline':
      'Menüs an deine Ziele angepasst in 30 Sekunden.\nOhne Stunden mit Nachdenken, Planen und Berechnen zu verbringen.',
    'footer.copyright': '© 2025 NutriZen. Alle Rechte vorbehalten.',
    'footer.disclaimer':
      'NutriZen ist ein Mahlzeitorganisationsassistent, kein Gesundheitsfachmann. Die bereitgestellten Informationen stellen keine medizinische Beratung dar. Konsultiere einen Arzt oder Ernährungsberater für personalisierte Beratung.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('nutrizen-language') as Language;
    return stored || 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('nutrizen-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
