import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'preheader.trial': '🎉 Essai gratuit 7 jours — Aucune CB requise — Garantie temps-gagné 30j',
    'signup.title': 'Commencer avec NutriZen',
    'signup.subtitle': 'Choisis ta formule pour créer ton compte',
    'signup.info': 'Pour garantir la qualité de notre service, la création de compte se fait uniquement via Stripe.',
    'signup.benefit': '🎁 7 jours d\'essai gratuit · Aucune carte bancaire requise',
    'signup.viewPlans': 'Voir les formules',
    'signup.hasAccount': 'Déjà un compte ?',
    'signup.login': 'Se connecter',
    'signup.backHome': '← Retour à l\'accueil',
    'header.advantages': 'Avantages',
    'header.howItWorks': 'Fonctionnement',
    'header.examples': 'Exemples',
    'header.pricing': 'Tarifs',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Se connecter',
    'header.cta': 'Commencer gratuitement',
    'hero.badge': '🔥 +1 000 utilisateurs',
    'hero.badgeSuffix': '· 92% prolongent après essai',
    'hero.title': 'Menus adaptés à tes objectifs en 30 secondes',
    'hero.subtitle': 'Sans passer des heures à réfléchir, planifier et calculer.',
    'hero.benefit1': 'Gagne 5h par semaine',
    'hero.benefit1Desc': 'sur ta planification repas',
    'hero.benefit2': 'Ton plan adapté',
    'hero.benefit2Desc': 'à tes objectifs (perte, maintien, prise)',
    'hero.benefit3': 'Plus de prise de tête',
    'hero.benefit3Desc': ': tout est calculé pour toi',
    'hero.cta': 'Commencer mon essai gratuit 7 jours',
    'hero.trial': 'Essai gratuit 7 jours',
    'hero.trialDetails': '· Aucun engagement · Aucune carte bancaire requise',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2 400 avis',
    'hero.cancelAnytime': 'Annulable en 3 clics',
    'hero.guarantee': 'Garantie temps-gagné 30j',
    'hero.validated': 'Validé par diététicien(ne)',
    'hero.menuGenerated': 'Menu généré',
    'hero.autoShoppingList': 'Courses auto',
    'benefits.title': 'Pourquoi choisir myNutriZen ?',
    'benefits.1.title': 'Gagne 5h par semaine',
    'benefits.1.result': 'Plus de temps pour toi',
    'benefits.1.description': 'Fini les 30 min quotidiennes à te demander "qu\'est-ce qu\'on mange ?". Tout est planifié automatiquement.',
    'benefits.2.title': 'Économise jusqu\'à 30%',
    'benefits.2.result': 'Liste de courses optimisée',
    'benefits.2.description': 'Ton plan génère une liste précise par rayon. Exit les achats impulsifs et le gaspillage.',
    'benefits.3.title': 'Zéro charge mentale',
    'benefits.3.result': 'Menus équilibrés automatiques',
    'benefits.3.description': 'Ton plan adapté à tes objectifs (perte, maintien, prise). Tout est calculé et prêt en 1 clic.',
    'howItWorks.title': 'Comment ça marche ?',
    'howItWorks.subtitle': '3 étapes simples pour simplifier tes repas',
    'howItWorks.step1.title': 'Réponds à 3 questions en 60 s',
    'howItWorks.step1.description': 'Profils, goûts, objectifs — on crée ton plan.',
    'howItWorks.step2.title': 'Reçois ton plan repas généré automatiquement',
    'howItWorks.step2.description': 'Chaque jour un menu complet adapté à ton rythme.',
    'howItWorks.step3.title': 'Swap libre & profite',
    'howItWorks.step3.description': 'Un plat ne te plaît pas ? Change-le en un clic. Gain de temps. Zéro stress.',
  },
  en: {
    'preheader.trial': '🎉 7-day free trial — No credit card required — 30-day time-saved guarantee',
    'signup.title': 'Get Started with NutriZen',
    'signup.subtitle': 'Choose your plan to create your account',
    'signup.info': 'To ensure the quality of our service, account creation is done exclusively via Stripe.',
    'signup.benefit': '🎁 7-day free trial · No credit card required',
    'signup.viewPlans': 'View Plans',
    'signup.hasAccount': 'Already have an account?',
    'signup.login': 'Sign in',
    'signup.backHome': '← Back to home',
    'header.advantages': 'Benefits',
    'header.howItWorks': 'How It Works',
    'header.examples': 'Examples',
    'header.pricing': 'Pricing',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Sign in',
    'header.cta': 'Get Started Free',
    'hero.badge': '🔥 +1,000 users',
    'hero.badgeSuffix': '· 92% continue after trial',
    'hero.title': 'Menus tailored to your goals in 30 seconds',
    'hero.subtitle': 'Without spending hours thinking, planning, and calculating.',
    'hero.benefit1': 'Save 5h per week',
    'hero.benefit1Desc': 'on your meal planning',
    'hero.benefit2': 'Your personalized plan',
    'hero.benefit2Desc': 'for your goals (loss, maintenance, gain)',
    'hero.benefit3': 'No more hassle',
    'hero.benefit3Desc': ': everything calculated for you',
    'hero.cta': 'Start my 7-day free trial',
    'hero.trial': '7-day free trial',
    'hero.trialDetails': '· No commitment · No credit card required',
    'hero.rating': '4.8/5',
    'hero.reviews': '+2,400 reviews',
    'hero.cancelAnytime': 'Cancel anytime in 3 clicks',
    'hero.guarantee': '30-day time-saved guarantee',
    'hero.validated': 'Dietitian validated',
    'hero.menuGenerated': 'Menu generated',
    'hero.autoShoppingList': 'Auto shopping list',
    'benefits.title': 'Why choose myNutriZen?',
    'benefits.1.title': 'Save 5h per week',
    'benefits.1.result': 'More time for you',
    'benefits.1.description': 'No more 30 daily minutes wondering "what to eat?". Everything is planned automatically.',
    'benefits.2.title': 'Save up to 30%',
    'benefits.2.result': 'Optimized shopping list',
    'benefits.2.description': 'Your plan generates a precise list by aisle. No more impulse purchases and waste.',
    'benefits.3.title': 'Zero mental load',
    'benefits.3.result': 'Automatic balanced menus',
    'benefits.3.description': 'Your plan adapted to your goals (loss, maintenance, gain). Everything calculated and ready in 1 click.',
    'howItWorks.title': 'How does it work?',
    'howItWorks.subtitle': '3 simple steps to simplify your meals',
    'howItWorks.step1.title': 'Answer 3 questions in 60s',
    'howItWorks.step1.description': 'Profiles, tastes, goals — we create your plan.',
    'howItWorks.step2.title': 'Receive your automatically generated meal plan',
    'howItWorks.step2.description': 'Every day a complete menu adapted to your rhythm.',
    'howItWorks.step3.title': 'Free swap & enjoy',
    'howItWorks.step3.description': 'Don\'t like a dish? Change it in one click. Time saved. Zero stress.',
  },
  es: {
    'preheader.trial': '🎉 Prueba gratuita de 7 días — Sin tarjeta de crédito — Garantía de tiempo ahorrado de 30 días',
    'signup.title': 'Comienza con NutriZen',
    'signup.subtitle': 'Elige tu plan para crear tu cuenta',
    'signup.info': 'Para garantizar la calidad de nuestro servicio, la creación de cuentas se realiza exclusivamente a través de Stripe.',
    'signup.benefit': '🎁 Prueba gratuita de 7 días · Sin tarjeta de crédito requerida',
    'signup.viewPlans': 'Ver Planes',
    'signup.hasAccount': '¿Ya tienes una cuenta?',
    'signup.login': 'Iniciar sesión',
    'signup.backHome': '← Volver al inicio',
    'header.advantages': 'Ventajas',
    'header.howItWorks': 'Cómo Funciona',
    'header.examples': 'Ejemplos',
    'header.pricing': 'Precios',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Iniciar sesión',
    'header.cta': 'Comenzar Gratis',
    'hero.badge': '🔥 +1.000 usuarios',
    'hero.badgeSuffix': '· 92% continúan después de la prueba',
    'hero.title': 'Menús adaptados a tus objetivos en 30 segundos',
    'hero.subtitle': 'Sin pasar horas pensando, planificando y calculando.',
    'hero.benefit1': 'Ahorra 5h por semana',
    'hero.benefit1Desc': 'en tu planificación de comidas',
    'hero.benefit2': 'Tu plan personalizado',
    'hero.benefit2Desc': 'para tus objetivos (pérdida, mantenimiento, ganancia)',
    'hero.benefit3': 'Sin complicaciones',
    'hero.benefit3Desc': ': todo calculado para ti',
    'hero.cta': 'Comenzar mi prueba gratuita de 7 días',
    'hero.trial': 'Prueba gratuita de 7 días',
    'hero.trialDetails': '· Sin compromiso · Sin tarjeta de crédito requerida',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2.400 reseñas',
    'hero.cancelAnytime': 'Cancela en cualquier momento en 3 clics',
    'hero.guarantee': 'Garantía de tiempo ahorrado de 30 días',
    'hero.validated': 'Validado por nutricionista',
    'hero.menuGenerated': 'Menú generado',
    'hero.autoShoppingList': 'Lista de compras automática',
    'benefits.title': '¿Por qué elegir myNutriZen?',
    'benefits.1.title': 'Ahorra 5h por semana',
    'benefits.1.result': 'Más tiempo para ti',
    'benefits.1.description': 'Se acabaron los 30 minutos diarios preguntándote "¿qué comemos?". Todo está planificado automáticamente.',
    'benefits.2.title': 'Ahorra hasta un 30%',
    'benefits.2.result': 'Lista de compras optimizada',
    'benefits.2.description': 'Tu plan genera una lista precisa por pasillo. Adiós a las compras impulsivas y el desperdicio.',
    'benefits.3.title': 'Cero carga mental',
    'benefits.3.result': 'Menús equilibrados automáticos',
    'benefits.3.description': 'Tu plan adaptado a tus objetivos (pérdida, mantenimiento, ganancia). Todo calculado y listo en 1 clic.',
    'howItWorks.title': '¿Cómo funciona?',
    'howItWorks.subtitle': '3 pasos simples para simplificar tus comidas',
    'howItWorks.step1.title': 'Responde 3 preguntas en 60s',
    'howItWorks.step1.description': 'Perfiles, gustos, objetivos: creamos tu plan.',
    'howItWorks.step2.title': 'Recibe tu plan de comidas generado automáticamente',
    'howItWorks.step2.description': 'Cada día un menú completo adaptado a tu ritmo.',
    'howItWorks.step3.title': 'Intercambio libre y disfruta',
    'howItWorks.step3.description': '¿No te gusta un plato? Cámbialo en un clic. Ahorro de tiempo. Cero estrés.',
  },
  de: {
    'preheader.trial': '🎉 7 Tage kostenlose Testversion — Keine Kreditkarte erforderlich — 30-Tage-Zeitersparnis-Garantie',
    'signup.title': 'Starte mit NutriZen',
    'signup.subtitle': 'Wähle deinen Plan, um dein Konto zu erstellen',
    'signup.info': 'Um die Qualität unseres Services zu gewährleisten, erfolgt die Kontoerstellung ausschließlich über Stripe.',
    'signup.benefit': '🎁 7 Tage kostenlose Testversion · Keine Kreditkarte erforderlich',
    'signup.viewPlans': 'Pläne ansehen',
    'signup.hasAccount': 'Hast du bereits ein Konto?',
    'signup.login': 'Anmelden',
    'signup.backHome': '← Zurück zur Startseite',
    'header.advantages': 'Vorteile',
    'header.howItWorks': 'Wie es funktioniert',
    'header.examples': 'Beispiele',
    'header.pricing': 'Preise',
    'header.faq': 'FAQ',
    'header.blog': 'Blog',
    'header.login': 'Anmelden',
    'header.cta': 'Kostenlos starten',
    'hero.badge': '🔥 +1.000 Nutzer',
    'hero.badgeSuffix': '· 92% verlängern nach der Testphase',
    'hero.title': 'Menüs an deine Ziele angepasst in 30 Sekunden',
    'hero.subtitle': 'Ohne Stunden mit Nachdenken, Planen und Berechnen zu verbringen.',
    'hero.benefit1': 'Spare 5h pro Woche',
    'hero.benefit1Desc': 'bei deiner Essensplanung',
    'hero.benefit2': 'Dein personalisierter Plan',
    'hero.benefit2Desc': 'für deine Ziele (Abnehmen, Erhaltung, Zunehmen)',
    'hero.benefit3': 'Kein Stress mehr',
    'hero.benefit3Desc': ': alles für dich berechnet',
    'hero.cta': 'Meine 7-tägige kostenlose Testversion starten',
    'hero.trial': '7 Tage kostenlose Testversion',
    'hero.trialDetails': '· Keine Verpflichtung · Keine Kreditkarte erforderlich',
    'hero.rating': '4,8/5',
    'hero.reviews': '+2.400 Bewertungen',
    'hero.cancelAnytime': 'Jederzeit in 3 Klicks kündbar',
    'hero.guarantee': '30-Tage-Zeitersparnis-Garantie',
    'hero.validated': 'Von Ernährungsberater validiert',
    'hero.menuGenerated': 'Menü generiert',
    'hero.autoShoppingList': 'Auto-Einkaufsliste',
    'benefits.title': 'Warum myNutriZen wählen?',
    'benefits.1.title': 'Spare 5h pro Woche',
    'benefits.1.result': 'Mehr Zeit für dich',
    'benefits.1.description': 'Keine 30 Minuten täglich mehr mit der Frage "Was essen wir?". Alles ist automatisch geplant.',
    'benefits.2.title': 'Spare bis zu 30%',
    'benefits.2.result': 'Optimierte Einkaufsliste',
    'benefits.2.description': 'Dein Plan erstellt eine präzise Liste nach Gang. Keine Impulskäufe und Verschwendung mehr.',
    'benefits.3.title': 'Null mentale Belastung',
    'benefits.3.result': 'Automatische ausgewogene Menüs',
    'benefits.3.description': 'Dein Plan angepasst an deine Ziele (Abnehmen, Erhaltung, Zunehmen). Alles berechnet und bereit in 1 Klick.',
    'howItWorks.title': 'Wie funktioniert es?',
    'howItWorks.subtitle': '3 einfache Schritte zur Vereinfachung deiner Mahlzeiten',
    'howItWorks.step1.title': 'Beantworte 3 Fragen in 60s',
    'howItWorks.step1.description': 'Profile, Geschmäcker, Ziele — wir erstellen deinen Plan.',
    'howItWorks.step2.title': 'Erhalte deinen automatisch generierten Essensplan',
    'howItWorks.step2.description': 'Jeden Tag ein komplettes Menü an deinen Rhythmus angepasst.',
    'howItWorks.step3.title': 'Freier Tausch & genieße',
    'howItWorks.step3.description': 'Magst du ein Gericht nicht? Ändere es mit einem Klick. Zeitersparnis. Null Stress.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('nutrizen-language') as Language;
    return stored || 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('nutrizen-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
