import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { withSecurity } from '../_shared/security.ts';
import { validate, UserIdSchema } from '../_shared/validation.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.75.0';

serve(async (req) => {
  return await withSecurity(req, {
    requireAuth: true,
    validateUserIdMatch: true,
    rateLimit: { maxTokens: 10, refillRate: 10, cost: 1 }, // Max 10 inits per minute
  }, async (context, body: { user_id?: string }, logger) => {
    
    // Validate user_id
    const user_id = body?.user_id || context.userId;
    validate(UserIdSchema, user_id);
    
    logger.info('Initializing user rows', { userId: user_id });
    
    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);
    
    // Verify the requesting user matches the user_id (or is admin)
    if (context.userId !== user_id) {
      const { data: roles } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', context.userId)
        .single();

      if (!roles || roles.role !== 'admin') {
        throw new Error('Unauthorized: Can only initialize your own rows');
      }
    }
    
    // Initialize user_dashboard_stats
    const { error: statsError } = await supabase
      .from('user_dashboard_stats')
      .upsert({
        user_id,
        temps_gagne: 0,
        charge_mentale_pct: 0,
        serie_en_cours_set_count: 0,
        credits_zen: 10,
        references_count: 0,
        objectif_hebdos_valide: 0,
      }, {
        onConflict: 'user_id'
      });

    if (statsError) {
      logger.error('Error initializing dashboard stats', statsError);
      throw new Error(`Failed to initialize dashboard stats: ${statsError.message}`);
    }

    // Initialize user_gamification
    const { error: gamificationError } = await supabase
      .from('user_gamification')
      .upsert({
        user_id,
        points: 0,
        level: 1,
        streak_days: 0,
        badges_count: 0,
      }, {
        onConflict: 'user_id'
      });

    if (gamificationError) {
      logger.error('Error initializing gamification', gamificationError);
      throw new Error(`Failed to initialize gamification: ${gamificationError.message}`);
    }

    // Initialize user_points
    const { error: pointsError } = await supabase
      .from('user_points')
      .upsert({
        user_id,
        total_points: 0,
        current_level: 'Bronze',
        login_streak: 0,
        meals_completed: 0,
        meals_generated: 0,
        referrals: 0,
      }, {
        onConflict: 'user_id'
      });

    if (pointsError) {
      logger.error('Error initializing points', pointsError);
      throw new Error(`Failed to initialize points: ${pointsError.message}`);
    }

    // Initialize user_profile (referral_code will be auto-generated by trigger)
    const { error: profileError } = await supabase
      .from('user_profiles')
      .upsert({
        id: user_id,
        display_name: null,
        avatar_url: null,
        show_on_leaderboard: true,
      }, {
        onConflict: 'id'
      });

    if (profileError) {
      logger.error('Error initializing profile', profileError);
      throw new Error(`Failed to initialize profile: ${profileError.message}`);
    }

    logger.info('Successfully initialized all rows', { userId: user_id });

    return { 
      success: true, 
      message: 'User rows initialized successfully',
      user_id
    };
  });
});
