-- Add comprehensive user preferences columns to preferences table
ALTER TABLE preferences
  ADD COLUMN IF NOT EXISTS sexe text,
  ADD COLUMN IF NOT EXISTS age integer,
  ADD COLUMN IF NOT EXISTS taille_cm integer,
  ADD COLUMN IF NOT EXISTS poids_actuel_kg numeric,
  ADD COLUMN IF NOT EXISTS poids_souhaite_kg numeric,
  ADD COLUMN IF NOT EXISTS niveau_activite text,
  ADD COLUMN IF NOT EXISTS metier text,
  ADD COLUMN IF NOT EXISTS objectif_principal text,
  ADD COLUMN IF NOT EXISTS duree_souhaitee text,
  ADD COLUMN IF NOT EXISTS repas_par_jour integer,
  ADD COLUMN IF NOT EXISTS portions_par_repas integer,
  ADD COLUMN IF NOT EXISTS temps_preparation text,
  ADD COLUMN IF NOT EXISTS batch_cooking text,
  ADD COLUMN IF NOT EXISTS niveau_cuisine text,
  ADD COLUMN IF NOT EXISTS frequence_repas_emporter text,
  ADD COLUMN IF NOT EXISTS ustensiles text[],
  ADD COLUMN IF NOT EXISTS autres_allergies text,
  ADD COLUMN IF NOT EXISTS type_alimentation text,
  ADD COLUMN IF NOT EXISTS aliments_eviter text[],
  ADD COLUMN IF NOT EXISTS ingredients_favoris text[],
  ADD COLUMN IF NOT EXISTS cuisine_preferee text[],
  ADD COLUMN IF NOT EXISTS produits_bio_locaux text,
  ADD COLUMN IF NOT EXISTS niveau_sel text,
  ADD COLUMN IF NOT EXISTS limiter_sucre boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS niveau_epices text,
  ADD COLUMN IF NOT EXISTS mode_cuisson_prefere text[],
  ADD COLUMN IF NOT EXISTS objectif_calorique text,
  ADD COLUMN IF NOT EXISTS repartition_macros text,
  ADD COLUMN IF NOT EXISTS apport_proteines_g_kg numeric,
  ADD COLUMN IF NOT EXISTS recettes_riches_fibres boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS produits_laitiers text,
  ADD COLUMN IF NOT EXISTS taille_portion text,
  ADD COLUMN IF NOT EXISTS cuisine_pour_enfants boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS nombre_enfants integer,
  ADD COLUMN IF NOT EXISTS age_enfants integer[],
  ADD COLUMN IF NOT EXISTS autres_adultes integer,
  ADD COLUMN IF NOT EXISTS allergies_proches text[],
  ADD COLUMN IF NOT EXISTS niveau_stress text,
  ADD COLUMN IF NOT EXISTS sommeil_heures numeric,
  ADD COLUMN IF NOT EXISTS motivation_principale text,
  ADD COLUMN IF NOT EXISTS principal_frein text,
  ADD COLUMN IF NOT EXISTS budget_hebdomadaire text,
  ADD COLUMN IF NOT EXISTS lieu_courses text,
  ADD COLUMN IF NOT EXISTS frequence_courses text,
  ADD COLUMN IF NOT EXISTS conseils_lifestyle boolean DEFAULT false;

-- Add comment to table
COMMENT ON TABLE preferences IS 'Comprehensive user preferences for personalized recipe recommendations';