
-- Add meat, fish, shellfish, alcohol, honey entries that were lost in failed migration
INSERT INTO public.restriction_dictionary (key, pattern, kind, priority) VALUES
('meat','viande','ingredient',10),
('meat','boeuf','ingredient',10),
('meat','veau','ingredient',10),
('meat','agneau','ingredient',10),
('meat','mouton','ingredient',10),
('meat','poulet','ingredient',10),
('meat','dinde','ingredient',10),
('meat','canard','ingredient',10),
('meat','lapin','ingredient',9),
('meat','gibier','ingredient',9),
('meat','chevreuil','ingredient',9),
('meat','sanglier','ingredient',9),
('meat','filet mignon','ingredient',9),
('meat','entrecote','ingredient',9),
('meat','steak','ingredient',9),
('meat','escalope','ingredient',9),
('meat','blanquette','ingredient',9),
('meat','roti','ingredient',9),
('meat','magret','ingredient',9),
('meat','hache','ingredient',8),
('fish','poisson','ingredient',10),
('fish','saumon','ingredient',10),
('fish','cabillaud','ingredient',10),
('fish','thon','ingredient',10),
('fish','truite','ingredient',10),
('fish','sardine','ingredient',10),
('fish','sole','ingredient',10),
('fish','merlu','ingredient',10),
('fish','dorade','ingredient',10),
('fish','colin','ingredient',10),
('fish','maquereau','ingredient',10),
('fish','anchois','ingredient',10),
('fish','tilapia','ingredient',10),
('shellfish','crevette','ingredient',10),
('shellfish','crevettes','ingredient',10),
('shellfish','moule','ingredient',10),
('shellfish','moules','ingredient',10),
('shellfish','homard','ingredient',10),
('shellfish','crabe','ingredient',10),
('shellfish','langoustine','ingredient',10),
('shellfish','calmar','ingredient',10),
('shellfish','poulpe','ingredient',10),
('shellfish','fruits de mer','ingredient',10),
('dairy','lait','ingredient',10),
('dairy','fromage','ingredient',10),
('dairy','beurre','ingredient',10),
('dairy','creme','ingredient',9),
('dairy','yaourt','ingredient',10),
('dairy','gruyere','ingredient',10),
('dairy','emmental','ingredient',10),
('dairy','parmesan','ingredient',10),
('dairy','mozzarella','ingredient',10),
('dairy','ricotta','ingredient',10),
('dairy','mascarpone','ingredient',10),
('dairy','feta','ingredient',10),
('dairy','bechamel','ingredient',9),
('dairy','creme fraiche','ingredient',10),
('eggs','oeuf','ingredient',10),
('eggs','oeufs','ingredient',10),
('gluten','farine','ingredient',10),
('gluten','pain','ingredient',10),
('gluten','pates','ingredient',10),
('gluten','spaghetti','ingredient',10),
('gluten','tagliatelle','ingredient',10),
('gluten','lasagne','ingredient',10),
('gluten','couscous','ingredient',10),
('gluten','semoule','ingredient',10),
('gluten','chapelure','ingredient',10),
('nuts','amande','ingredient',10),
('nuts','amandes','ingredient',10),
('nuts','noix','ingredient',10),
('nuts','noisette','ingredient',10),
('nuts','noisettes','ingredient',10),
('nuts','cajou','ingredient',10),
('nuts','pistache','ingredient',10),
('peanuts','cacahuete','ingredient',10),
('peanuts','arachide','ingredient',10),
('peanuts','arachides','ingredient',10),
('soy','soja','ingredient',10),
('soy','tofu','ingredient',10),
('soy','edamame','ingredient',10),
('soy','miso','ingredient',10),
('soy','tempeh','ingredient',10),
('soy','sauce soja','ingredient',10),
('sesame','tahini','ingredient',10),
('alcohol','vin','ingredient',9),
('alcohol','vin blanc','ingredient',10),
('alcohol','vin rouge','ingredient',10),
('alcohol','alcool','ingredient',10),
('honey','miel','ingredient',10)
ON CONFLICT DO NOTHING;

-- Re-backfill ALL recipes with improved dictionary
UPDATE public.recipes r
SET ingredient_keys = public.recipe_ingredient_keys(r)
WHERE published = true;
